### ISSUE TITLE
A few components don't work on `https`

### ISSUE THREAD

**Issue by lepisma** [pravj/pravj.github.io#4]
Hi,

Your recent [blog post](https://pravj.github.io/blog/information-dynamics-on-github/) has issues with `https` (major one being the d3 chart for stargazer network not being rendered and a couple of css files). Works well when using `http`. I guess, using https for request urls should do.

PS: great post btw !

**Comment by pravj** [comment]
Thanks! Abhinav, that's a big save.

It should work fine now.
